// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAInFfieopCPBix0QO2QzNmwwIlXSU_KEU',
    appId: '1:154722549550:web:463c1baad9d0e602d084bf',
    messagingSenderId: '154722549550',
    projectId: 'smart-medicine-box-c4058',
    authDomain: 'smart-medicine-box-c4058.firebaseapp.com',
    databaseURL: 'https://smart-medicine-box-c4058-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-c4058.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwLQcD62d9Udu-stZBnna16nshS4enco',
    appId: '1:154722549550:android:506be3be8de7edf7d084bf',
    messagingSenderId: '154722549550',
    projectId: 'smart-medicine-box-c4058',
    databaseURL: 'https://smart-medicine-box-c4058-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-c4058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljCbJ09VDcte66uukvSOxvj9wIO9qv6M',
    appId: '1:154722549550:ios:e6e005d113070717d084bf',
    messagingSenderId: '154722549550',
    projectId: 'smart-medicine-box-c4058',
    databaseURL: 'https://smart-medicine-box-c4058-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-c4058.firebasestorage.app',
    iosBundleId: 'com.example.medicinetreatment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAljCbJ09VDcte66uukvSOxvj9wIO9qv6M',
    appId: '1:154722549550:ios:e6e005d113070717d084bf',
    messagingSenderId: '154722549550',
    projectId: 'smart-medicine-box-c4058',
    databaseURL: 'https://smart-medicine-box-c4058-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-c4058.firebasestorage.app',
    iosBundleId: 'com.example.medicinetreatment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAInFfieopCPBix0QO2QzNmwwIlXSU_KEU',
    appId: '1:154722549550:web:1eec39b83990ec1ad084bf',
    messagingSenderId: '154722549550',
    projectId: 'smart-medicine-box-c4058',
    authDomain: 'smart-medicine-box-c4058.firebaseapp.com',
    databaseURL: 'https://smart-medicine-box-c4058-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-c4058.firebasestorage.app',
  );
}
