// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYuQJQzwOwCMSL7JhNUHFg6et3YdYE3fg',
    appId: '1:958726952762:web:20876cfb35e8d198876203',
    messagingSenderId: '958726952762',
    projectId: 'smart-medicine-box-9ecee',
    authDomain: 'smart-medicine-box-9ecee.firebaseapp.com',
    databaseURL: 'https://smart-medicine-box-9ecee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-9ecee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevcFf56aVNUeLfqlAiISZfQfqUvOG0v0',
    appId: '1:958726952762:android:cd823d4be9648026876203',
    messagingSenderId: '958726952762',
    projectId: 'smart-medicine-box-9ecee',
    databaseURL: 'https://smart-medicine-box-9ecee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-9ecee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivbszQbsuVQUkpPmP9px-09UHCzbxcgg',
    appId: '1:958726952762:ios:dc32afdbfc6d265e876203',
    messagingSenderId: '958726952762',
    projectId: 'smart-medicine-box-9ecee',
    databaseURL: 'https://smart-medicine-box-9ecee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-9ecee.firebasestorage.app',
    iosBundleId: 'com.example.medicinetreatment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivbszQbsuVQUkpPmP9px-09UHCzbxcgg',
    appId: '1:958726952762:ios:dc32afdbfc6d265e876203',
    messagingSenderId: '958726952762',
    projectId: 'smart-medicine-box-9ecee',
    databaseURL: 'https://smart-medicine-box-9ecee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-9ecee.firebasestorage.app',
    iosBundleId: 'com.example.medicinetreatment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYuQJQzwOwCMSL7JhNUHFg6et3YdYE3fg',
    appId: '1:958726952762:web:9387f961cbe616c2876203',
    messagingSenderId: '958726952762',
    projectId: 'smart-medicine-box-9ecee',
    authDomain: 'smart-medicine-box-9ecee.firebaseapp.com',
    databaseURL: 'https://smart-medicine-box-9ecee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-medicine-box-9ecee.firebasestorage.app',
  );

}